# Generated by Django 4.0.5 on 2022-06-20 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_delete_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.lineid')),
                ('personal_id', models.IntegerField()),
            ],
        ),
    ]
