# Generated by Django 4.0.5 on 2022-06-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_employee_user_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='LineID',
        ),
    ]
